.nh
.TH "pogo" "1" "Feb 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-assets-list - List all assets in the repository


.SH SYNOPSIS
\fBpogo assets list [flags]\fP


.SH DESCRIPTION
List all assets in the repository.

.PP
This shows all uploaded assets with their names/paths.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
  # List all assets
  pogo assets list

  # Using the short alias
  pogo assets ls
.EE


.SH SEE ALSO
\fBpogo-assets(1)\fP
