.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-whoami - Show personal access token for current repository


.SH SYNOPSIS
\fBpogo whoami [flags]\fP


.SH DESCRIPTION
Show the personal access token being used for the current repository


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for whoami


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH SEE ALSO
\fBpogo(1)\fP
