.nh
.TH "pogo" "1" "Jan 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-invite - Manage user invitations


.SH SYNOPSIS
\fBpogo invite [flags]\fP


.SH DESCRIPTION
Manage user invitations


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for invite


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-invite-create(1)\fP, \fBpogo-invite-list(1)\fP
