.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-daemon-install - Install Pogo daemon service


.SH SYNOPSIS
\fBpogo daemon install [flags]\fP


.SH DESCRIPTION
Install the Pogo daemon service to run automatically.

.PP
This will create the necessary service configuration files and register
the daemon with the system service manager.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for install


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo-daemon(1)\fP
