.nh
.TH "pogo" "1" "Feb 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-ci-runs - Inspect CI run history


.SH SYNOPSIS
\fBpogo ci runs [flags]\fP


.SH DESCRIPTION
Commands for listing and inspecting CI runs recorded on the server.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for runs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo-ci(1)\fP, \fBpogo-ci-runs-inspect(1)\fP, \fBpogo-ci-runs-list(1)\fP
