.nh
.TH "pogo" "1" "Feb 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-assets-delete - Delete an asset


.SH SYNOPSIS
\fBpogo assets delete  [flags]\fP


.SH DESCRIPTION
Delete an asset from the repository.

.PP
This permanently removes the asset from the server.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
  # Delete an asset
  pogo assets delete release/v0.9/binary

  # Using the short alias
  pogo assets rm old-release.tar.gz
.EE


.SH SEE ALSO
\fBpogo-assets(1)\fP
