.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-bookmark-list - List all bookmarks in the repository


.SH SYNOPSIS
\fBpogo bookmark list [flags]\fP


.SH DESCRIPTION
List all bookmarks in the repository along with the changes they point to.

.PP
This shows you all named references in your repository, making it easy to
see important versions, releases, and the current "main" branch.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH EXAMPLE
.EX
  # List all bookmarks
  pogo bookmark list

  # Using the short alias
  pogo b l
.EE


.SH SEE ALSO
\fBpogo-bookmark(1)\fP
