.nh
.TH "pogo" "1" "Feb 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-push - Push all changes to the configured Pogo server


.SH SYNOPSIS
\fBpogo push [flags]\fP


.SH DESCRIPTION
Push all local changes to the configured Pogo server.

.PP
This command uploads all modified, added, and deleted files to the server,
updating the current change. Unlike Git, you don't need to stage files first,
all changes in your working directory are pushed.

.PP
The push might be rejected if:
- The current change is read-only (has children or bookmarks pointing to it)
- You don't have write permissions to the repository
- Network or server issues occur

.PP
Use the --force flag to override read-only protection, but be careful as this
can break the history for other users.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force push even if the change is readonly

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for push


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
# Push all changes to the server
pogo push

# Force push even if the change is read-only (use with caution!)
pogo push --force

# Short form of force push
pogo push -f
.EE


.SH SEE ALSO
\fBpogo(1)\fP
