.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-daemon - Manage Pogo daemon service


.SH SYNOPSIS
\fBpogo daemon [flags]\fP


.SH DESCRIPTION
Manage the Pogo daemon service for automatic operations.

.PP
This is currently only implemented for macOS. Windows and Linux will follow soon.

.PP
The daemon service can be installed to run automatically and provides
background functionality for Pogo operations.

.PP
This daemon is not required but it allows for automatic pushing of any changes.
You can tweak its behaviour by editing the global configuration file which is located at your system's default config directory.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for daemon


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-daemon-install(1)\fP, \fBpogo-daemon-start(1)\fP, \fBpogo-daemon-stop(1)\fP, \fBpogo-daemon-uninstall(1)\fP