.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-bookmark - Manage bookmarks


.SH SYNOPSIS
\fBpogo bookmark [flags]\fP


.SH DESCRIPTION
Manage bookmarks


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bookmark


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-bookmark-list(1)\fP, \fBpogo-bookmark-set(1)\fP
