.nh
.TH "pogo" "1" "Feb 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-bookmark - Manage bookmarks for changes


.SH SYNOPSIS
\fBpogo bookmark [flags]\fP


.SH DESCRIPTION
Manage bookmarks that point to specific changes in your repository.

.PP
Bookmarks in Pogo are similar to tags and branches in Git combined. They are
named references to specific changes that make it easy to find important
versions of your code.

.PP
Common bookmark patterns:
- "main" - The current production/stable version (treated specially by Pogo)
- "v1.0.0", "v2.1.3" - Semantic version tags for releases
- "feature-xyz" - Mark the completion of a feature
- "before-refactor" - Mark a point before major changes

.PP
The "main" bookmark is special, it's treated as the default branch and is
what new users will see when they clone your repository.

.PP
This command pushes any changes before running.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bookmark


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-bookmark-list(1)\fP, \fBpogo-bookmark-remove(1)\fP, \fBpogo-bookmark-set(1)\fP
