.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-init - Initialize a new repository on a given Pogo server


.SH SYNOPSIS
\fBpogo init [flags]\fP


.SH DESCRIPTION
Initialize a new Pogo repository in the current directory.

.PP
This command creates a new repository on the specified Pogo server and configures
the current directory to track it. A .pogo.yaml file will be created to store
the repository configuration.

.PP
The repository can be made public (read-only access for everyone) or kept private
(requires authentication for all access).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for init

.PP
\fB--name\fP=""
	repository name

.PP
\fB--public\fP[=false]
	make repository public

.PP
\fB--server\fP=""
	host:port


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
# Initialize a private repository
pogo init --server localhost:8080 --name my-project

# Initialize a public repository
pogo init --server pogo.example.com:8080 --name open-source-project --public
.EE


.SH SEE ALSO
\fBpogo(1)\fP
