.nh
.TH "pogo" "1" "Dec 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-edit - Switch to a different change for editing


.SH SYNOPSIS
\fBpogo edit  [flags]\fP


.SH DESCRIPTION
Switch your working directory to a different change for editing.

.PP
This command downloads all files from the specified change and replaces your
current working directory contents with them. It's similar to 'git checkout'
but in Pogo's centralized model.

.PP
Important notes:
- Any uncommitted local changes will be pushed to the current change before switching
- The change you switch to becomes your new working change
- You can edit any change, even if it has children (though pushing will require --force)
- Files in .pogoignore are not affected by this operation

.PP
Use this command to:
- Switch between different lines of development
- Go back to an earlier version to fix a bug
- Review someone else's changes
- Start working from a different base

.PP
This command pushes any changes before running.


.SH OPTIONS
\fB-f\fP, \fB--force\fP[=false]
	Force push even if the change is readonly

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for edit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
# Switch to change ab23
pogo edit ab23

# Switch to the change marked as "main"
pogo edit main

# Switch to a tagged release
pogo edit v1.0.0

# Use the checkout alias (familiar to Git users)
pogo checkout feature-branch
.EE


.SH SEE ALSO
\fBpogo(1)\fP
