.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
\fBpogo completion [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for pogo for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-completion-bash(1)\fP, \fBpogo-completion-fish(1)\fP, \fBpogo-completion-powershell(1)\fP, \fBpogo-completion-zsh(1)\fP
