.nh
.TH "pogo" "1" "Jan 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-secrets - Manage repository secrets for CI pipelines


.SH SYNOPSIS
\fBpogo secrets [flags]\fP


.SH DESCRIPTION
Manage secrets that can be accessed in CI pipeline configurations.

.PP
Secrets are encrypted values that can be referenced in your CI pipeline YAML
files using the {{ secret "KEY" }} template function. They are useful for
storing sensitive data like API tokens, deployment keys, and credentials.

.PP
Secrets are scoped to a repository and can only be accessed by users with
access to that repository.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for secrets


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-secrets-delete(1)\fP, \fBpogo-secrets-get(1)\fP, \fBpogo-secrets-list(1)\fP, \fBpogo-secrets-set(1)\fP
