.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-describe - Set the change description


.SH SYNOPSIS
\fBpogo describe [flags]\fP


.SH DESCRIPTION
Display the change history as parent/child relations


.SH OPTIONS
\fB-m\fP, \fB--description\fP=""
	Description for the change

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for describe


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH SEE ALSO
\fBpogo(1)\fP
