.nh
.TH "pogo" "1" "Jan 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-secrets-set - Set a secret value


.SH SYNOPSIS
\fBpogo secrets set   [flags]\fP


.SH DESCRIPTION
Set a secret value for the repository.

.PP
If a secret with the same key already exists, it will be updated with the
new value. Secrets can be used in CI pipeline configurations.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
  # Set a secret
  pogo secrets set DEPLOY_TOKEN abc123xyz

  # Update an existing secret
  pogo secrets set API_KEY new-key-value

  # Using the short alias
  pogo secrets s DATABASE_URL postgres://...
.EE


.SH SEE ALSO
\fBpogo-secrets(1)\fP
