.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-info - Display the current working copy status


.SH SYNOPSIS
\fBpogo info [flags]\fP


.SH DESCRIPTION
Display information about the current working copy and repository status.

.PP
This command is particularly useful for:
- Checking which change you're currently working on
- Seeing if there are any conflicts
- Integrating Pogo status into your shell prompt
- Scripting and automation

.PP
The output can be customized using Go's text/template syntax with the --format flag.

.PP
Available template variables:
  {{.ChangeNamePrefix}}   - The adjective part of the change name
.br
  {{.ChangeNameSuffix}}   - The noun and number part of the change name
.br
  {{.ChangeName}}         - The full change name (prefix + suffix)
.br
  {{.ChangeDescription}}  - The description of the current change
.br
  {{.Bookmarks}}          - Array of bookmarks pointing to this change
.br
  {{.IsInConflict}}       - Boolean indicating if the change has conflicts
.br
  {{.Error}}              - Any error message (connection issues, etc.)

.PP
The default format shows a colored prompt-friendly output with conflict
indicators and bookmark information.


.SH OPTIONS
\fB--format\fP="({{if .Error}}\\x1b[31m{{.Error}}\\x1b[0m{{else}}{{if .IsInConflict}}💥{{end}}\\x1b[35m{{.ChangeNamePrefix}}\\x1b[90m{{.ChangeNameSuffix}}\\x1b[0m {{- range $i, $b := .Bookmarks}}{{if $i}}, {{else}} {{end}}{{if eq . \\"main\\"}}\\x1b[32m{{.}}\\x1b[0m{{else}}{{.}}{{end}}{{end}}{{end}})"
	Format string for the prompt output

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for info


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH EXAMPLE
.EX
# Show default formatted info
pogo info

# Simple format showing just the change name
pogo info --format '{{.ChangeName}}'

# Format for shell prompt showing change and bookmarks
pogo info --format '({{.ChangeName}}{{range .Bookmarks}} [{{.}}]{{end}})'

# Show description if available
pogo info --format '{{.ChangeName}}: {{.ChangeDescription}}'

# Bash prompt integration example
export PS1='$(pogo info --format "{{.ChangeName}}") \\$ '

# Check for conflicts in a script
pogo info --format '{{.IsInConflict}}'
.EE


.SH SEE ALSO
\fBpogo(1)\fP
