.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-rm - Remove a change


.SH SYNOPSIS
\fBpogo rm  [flags]\fP


.SH DESCRIPTION
Remove a change from the repository.
By default, all children of the change are also removed recursively.
Use --keep-children to only remove the specified change and move its children to its parents.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rm

.PP
\fB--keep-children\fP[=false]
	Only remove the specified change and move its children to its parents


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH SEE ALSO
\fBpogo(1)\fP
