.nh
.TH "pogo" "1" "Jan 2026" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-secrets-get - Get the value of a secret


.SH SYNOPSIS
\fBpogo secrets get  [flags]\fP


.SH DESCRIPTION
Get the value of a secret by its key.

.PP
This will display the secret value in plain text, so be careful when using
this command in shared or recorded terminal sessions.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
  # Get a secret value
  pogo secrets get DEPLOY_TOKEN

  # Using the short alias
  pogo secrets g API_KEY
.EE


.SH SEE ALSO
\fBpogo-secrets(1)\fP
