.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-bookmark-set - Set a bookmark


.SH SYNOPSIS
\fBpogo bookmark set [flags]\fP


.SH DESCRIPTION
Set a bookmark


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH EXAMPLE
.EX
pogo bookmark set main abc123
.EE


.SH SEE ALSO
\fBpogo-bookmark(1)\fP
