.nh
.TH "pogo" "1" "Dec 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-daemon-uninstall - Uninstall Pogo daemon service


.SH SYNOPSIS
\fBpogo daemon uninstall [flags]\fP


.SH DESCRIPTION
Uninstall the Pogo daemon service from the system.

.PP
This will remove the service configuration files and unregister the daemon
with the system service manager.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for uninstall


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo-daemon(1)\fP
