.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-ci-runs-inspect - Inspect the log output of a CI run


.SH SYNOPSIS
\fBpogo ci runs inspect  [flags]\fP


.SH DESCRIPTION
Inspect the log output of a CI run


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for inspect


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo-ci-runs(1)\fP