.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-daemon-start - Start the Pogo daemon service


.SH SYNOPSIS
\fBpogo daemon start [flags]\fP


.SH DESCRIPTION
Start the Pogo daemon service process.

.PP
This command starts the daemon and waits for it to gracefully shutdown.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for start


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo-daemon(1)\fP
