.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-secrets-delete - Delete a secret


.SH SYNOPSIS
\fBpogo secrets delete  [flags]\fP


.SH DESCRIPTION
Delete a secret from the repository.

.PP
This permanently removes the secret. Any CI pipelines that reference this
secret will receive an empty string when accessing it.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH EXAMPLE
.EX
  # Delete a secret
  pogo secrets delete OLD_TOKEN

  # Using the short alias
  pogo secrets d UNUSED_KEY
.EE


.SH SEE ALSO
\fBpogo-secrets(1)\fP