.nh
.TH "pogo" "1" "Sep 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-edit - Sets the specified revision as the working-copy revision


.SH SYNOPSIS
\fBpogo edit [change name] [flags]\fP


.SH DESCRIPTION
Downloads all files from the specified revision and replaces the working-copy files with it.
Ignored files are excluded.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for edit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-pager\fP[=false]
	Disable pager for all output

.PP
\fB--time\fP[=false]
	Measure command execution time


.SH SEE ALSO
\fBpogo(1)\fP
