.nh
.TH "pogo" "1" "Oct 2025" "pogo/dev" "Pogo Manual"

.SH NAME
pogo-ci - Manage CI pipelines


.SH SYNOPSIS
\fBpogo ci [flags]\fP


.SH DESCRIPTION
Commands for working with CI pipelines


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ci


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--time\fP[=false]
	Measure command execution time

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose debug logging


.SH SEE ALSO
\fBpogo(1)\fP, \fBpogo-ci-test(1)\fP
